name: Post Reminder to Mastodon

on:
  workflow_dispatch: # Allows the workflow to be manually triggered
  schedule:
    - cron: '0 8,12,15 * * *'

jobs:
  post_to_mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-dotenv Mastodon.py

      - name: Test
        run: |
          if [ -z "${{ secrets.API_BASE_URL }}" ]; then echo "API_BASE_URL is not set"; else echo "API_BASE_URL is set"; fi
          if [ -z "${{ secrets.MASTODON_ACCOUNT }}" ]; then echo "MASTODON_ACCOUNT is not set"; else echo "MASTODON_ACCOUNT is set"; fi
          if [ -z "${{ secrets.MESSAGE }}" ]; then echo "MESSAGE is not set"; else echo "MESSAGE is set"; fi
          if [ -z "${{ secrets.SECRET_KEY }}" ]; then echo "SECRET_KEY is not set"; else echo "SECRET_KEY is set"; fi

      - name: Run script
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          MASTODON_ACCOUNT: ${{ secrets.MASTODON_ACCOUNT }}
          MESSAGE: ${{ secrets.MESSAGE }}
        run: python send_reminder.py
